### ISSUE TITLE
Rendering very dark items in animation mode causes the output gif to break

### ISSUE THREAD

**Issue by Tslat** [AterAnimAvis/BlockRenderer#17]
As title - if you give the animation renderer a rather dark item to render, it fails to correctly output the gif.

What the thing looks like to try and render:
https://static.wikia.nocookie.net/adventofascension_gamepedia/images/1/18/Dustopia_Portal.gif/revision/latest?cb=20200126132439

What the animation renderer outputs:
![Render](https://user-images.githubusercontent.com/7098525/104415952-a8425a00-55be-11eb-9f15-37ceeaa5c1a8.gif)

**Comment by Tslat** [comment]
Scratch that, it seems to happen to other items, even when not dark...

Original:
https://static.wikia.nocookie.net/adventofascension_gamepedia/images/e/e4/Gardencia_Portal.gif/revision/latest?cb=20200126132401


Render from mod:
![Render 2](https://user-images.githubusercontent.com/7098525/104416526-b2188d00-55bf-11eb-84ef-2b55dce220ba.gif)


Worth noting, this occurs with auto loop turned on or off, but if it's on, I notice the auto loop takes a lot longer - sometimes going up to 60-80 instead of the normal values it gets to

**Comment by Tslat** [comment]
This one seems to break it _entirely_

https://static.wikia.nocookie.net/adventofascension_gamepedia/images/1/17/Iromine_Portal.gif/revision/latest?cb=20200126132404

Render output here:
![2021-01-13_16 53 58_Iromine Portal](https://user-images.githubusercontent.com/7098525/104416830-2d7a3e80-55c0-11eb-8838-127fdb86a538.gif)

It's actually completely invisible, but this is what it looks like next to the other renders of the same block shape, for comparison:
![image](https://user-images.githubusercontent.com/7098525/104416866-39660080-55c0-11eb-8c45-b78746a72183.png)

**Comment by AterAnimAvis** [comment]
Seems to be an issue with the underlying gif writer (Or the metadata I provide), writing out the source data seperate show that individual frames are being renderered correctly.

This will probably be fixed with the migration from AWT (See #14).

I've provided a temporary stopgap where you can render the animation to a zip containing each frame. There should be tools available to convert the collection of png's into a gif (ImageMagick, ffmpeg, etc). Sorry whilst it's not ideal its the quickest 'fix' I can provide at the moment.

**Comment by AterAnimAvis** [comment]
Looks like the new GifWriter (from the AWT migration) will fix this.

The code still needs some cleanup but hopefully I can finish up the migration this weekend and release `1.5.0`.

<details>
<summary>Images</summary>

![Iromine Portal](https://user-images.githubusercontent.com/8502446/106331568-13598500-627d-11eb-9b6f-24a515bacec6.gif)
![Dustopia](https://user-images.githubusercontent.com/8502446/106331572-148ab200-627d-11eb-8abd-9c05ac3ea3a0.gif)
</details>
