### ISSUE TITLE
The render gui will sometimes softlock on the text field when cleared

### ISSUE THREAD

**Issue by Tslat** [AterAnimAvis/BlockRenderer#18]
If you open the GUI (Ctrl + `) and go into either static or animated render, then click on the text box and backspace until the field is empty, sometimes the text field will then refuse to take any input, even though the gui itself is still operational.
This is fixed by closing and reopening the GUI.

Video example:

https://user-images.githubusercontent.com/7098525/104416263-3d455300-55bf-11eb-8cbf-3a1b0fc0d4f6.mp4

**Comment by AterAnimAvis** [comment]
Can replicate by clicking first on the size slider. Fixed in local.
